### ISSUE TITLE
ValueError: Can't write images with one color channel.

### ISSUE THREAD

**Issue by song-wensong** [BrianPulfer/PapersReimplementations#12]
I use the command `python ddpm.py` to train the model.
And it reports error:
``` python
Loss at epoch 20: 0.030 --> Best model ever (stored)33.81it/s]
Training progress: 100%|██████████| 20/20 [04:43<00:00, 14.17s/it]
Traceback (most recent call last):                            
  File "ddpm.py", line 256, in <module>
    main()
  File "ddpm.py", line 246, in main
    generated = generate_new_images(
  File "ddpm.py", line 138, in generate_new_images
    writer.append_data(frame)
  File "/mnt/petrelfs/songwensong/miniconda3/envs/ddpm/lib/python3.8/site-packages/imageio/v2.py", line 226, in append_data
    return self.instance.write(im, **self.write_args)
  File "/mnt/petrelfs/songwensong/miniconda3/envs/ddpm/lib/python3.8/site-packages/imageio/plugins/pillow.py", line 405, in write
    raise ValueError("Can't write images with one color channel.")
ValueError: Can't write images with one color channel.
```

I don't know why.

**Comment by BrianPulfer** [comment]
Hi @song-wensong! I just double-checked and the code seems to work on my machine. What version of `imageio` are you using? Version `2.25.1` works on a Linux machine. Alternatively, you can convert the grayscale image to an RGB image in line 130:

from 
`frame = frame.cpu().numpy().astype(np.uint8)`
to 
`frame = frame.repeat(1, 1, 3).cpu().numpy().astype(np.uint8)`

Let me know if this helps!

**Comment by song-wensong** [comment]
> Hi @song-wensong! I just double-checked and the code seems to work on my machine. What version of `imageio` are you using? Version `2.25.1` works on a Linux machine. Alternatively, you can convert the grayscale image to an RGB image in line 130:
> 
> from `frame = frame.cpu().numpy().astype(np.uint8)` to `frame = frame.repeat(1, 1, 3).cpu().numpy().astype(np.uint8)`
> 
> Let me know if this helps!

Thank you very much! It works after I convert the grayscale image to an RGB image in line 130.

I have another question, if I want to use the Multi-Task Facial Landmark (MTFL) dataset to train the model. How could I modify the code? :)

**Comment by BrianPulfer** [comment]
Hmm I am not familiar with this dataset, but in principle, you would just need to find the way to load it, create a new `DataLoader` for your dataset and the rest can remain as is. 

However, if you are more interested in getting good results than understanding the concepts behind DDPMs, I strongly suggest that you use a library (e.g. [diffusers](https://huggingface.co/docs/diffusers/index)) which comes with stronger architectures and are overall just better than this short introductory script 😄
