### ISSUE TITLE
patchify for loop ranges

### ISSUE THREAD

**Issue by baxterai** [BrianPulfer/PapersReimplementations#3]
Note there is an issue in patchify(), introduced by commit "Added patchify method which keeps positional information." (7cffc6c1e4afddb9d0b0bd4e925c5a4071fad0c1);
```
for i in range(h // n_patches):
    for j in range(w // n_patches):
```
It can be changed to;
```
for i in range(n_patches):
    for j in range(n_patches):
```

**Comment by BrianPulfer** [comment]
Dear @baxterai,

Thank you for your contribution. Yes, the change looks okay to me. S

**Comment by BrianPulfer** [comment]
Dear @baxterai,

Thank you very much for your contribution. Yes, your change looks good to me. You can send a pull request.
