### ISSUE TITLE
VIT Paper implemantation

### ISSUE THREAD

**Issue by satwiksunnam19** [BrianPulfer/PapersReimplementations#6]
Hello @BrianPulfer @baxterai 

In implementation , in the part of  [n,c,w,h=images.shape] how can we get the 4 dimensions for a 3 dimensional image. it's showing an error at that point and also as in the paper of VIT, the value of n is given by h*w/n_patches**2, which is not seen in the code part. 

can you please resolve this as soon as possible

Thanks,
Satwik Sunnam

**Comment by BrianPulfer** [comment]
Dear @satwiksunnam19,

The fourth dimension (n) is the number of images in a batch. You need to pass the images as a batch as is usually done in ML frameworks and in PyTorch code. If you are only feeding one image, you can convert it to a batch by running something like:

`batch = image.unsqueeze(0)`

Hope this helps.

**Comment by satwiksunnam19** [comment]
> Dear @satwiksunnam19,
> 
> The fourth dimension (n) is the number of images in a batch. You need to pass the images as a batch as is usually done in ML frameworks and in PyTorch code. If you are only feeding one image, you can convert it to a batch by running something like:
> 
> `batch = image.unsqueeze(0)`
> 
> Hope this helps.
> 

I'm hopefully doing with batches and please look at this code which I'm sharing
 https://www.kaggle.com/code/robber19/vit-try/notebook

It's showing error when I'm trying to do so.

**Comment by satwiksunnam19** [comment]
@BrianPulfer  @baxterai 
this is the error that I'm getting "RuntimeError: shape '[0, 16384, 48]' is invalid for the input of size 4194304" https://www.kaggle.com/code/robber19/vit-try/notebook
