### ISSUE TITLE
Using cifar10 dataset 

### ISSUE THREAD

**Issue by mehrshadmmt** [BrianPulfer/PapersReimplementations#8]
Hi, how can I use cifar10 as 3 channel images in this code? witch features should I changes?

**Comment by BrianPulfer** [comment]
Dear @mehrshadmmt,

Which implementation are you referring to? `ViT` or `DDPM`? In both cases, you simply need to change the dataset used and adjust the number of input channels (and output channels for DDPM) from 1 to 3.

Best,
Brian

**Comment by mehrshadmmt** [comment]
Thanks for your answer. I'm trying to train VIT model on cifar10. For this reason I changed the input dimensions to (3,32,32) but after that when I run the code, faced with some error:
` The expanded size of the tensor (16) must match the existing size (48) at non-singleton dimension 0.  Target sizes: [16].  Tensor sizes: [48]`
After that I changed something in patchify function. but again I faced with this error:
`The size of tensor a (193) must match the size of tensor b (65) at non-singleton dimension 1`
please help me to solve it.

**Comment by mehrshadmmt** [comment]
Thank you for help me to solve this problem.
I changed the part of code that you mentioned 
it worked and its training.
Thanks.
